//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesBlogSite.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeriesBlogSiteEntities : DbContext
    {
        public SeriesBlogSiteEntities()
            : base("name=SeriesBlogSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_about> tbl_about { get; set; }
        public virtual DbSet<tbl_blog> tbl_blog { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_comment> tbl_comment { get; set; }
        public virtual DbSet<tbl_communication> tbl_communication { get; set; }
        public virtual DbSet<tbl_type> tbl_type { get; set; }
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
    }
}
