//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesBlogSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_communication
    {
        public int cmm_id { get; set; }
        public string cmm_nameSurname { get; set; }
        public string cmm_mail { get; set; }
        public string cmm_tel { get; set; }
        public string cmm_subject { get; set; }
        public string cmm_message { get; set; }
    }
}
