//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesBlogSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_blog()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
        }
    
        public int blg_id { get; set; }
        public string blg_title { get; set; }
        public string blg_contents { get; set; }
        public Nullable<System.DateTime> blg_date { get; set; }
        public string blg_picture { get; set; }
        public Nullable<byte> blg_type { get; set; }
        public Nullable<byte> blg_category { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_type tbl_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_comment> tbl_comment { get; set; }
    }
}
