//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesBlogSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public int cmt_id { get; set; }
        public string cmt_name { get; set; }
        public string cmt_mail { get; set; }
        public string cmt_message { get; set; }
        public Nullable<int> cmt_blog { get; set; }
    
        public virtual tbl_blog tbl_blog { get; set; }
    }
}
